package com.example.myapplication.model

data class AppStrings(
    val appSubtitle: String,
    val createEntry: String,
    val songCover: String,
    val song: String,
    val artist: String,
    val date: String,
    val moodQuestion: String,
    val lyricSnippet: String,
    val createButton: String,
    val allDiaries: String,
    val noDiaries: String,
    val noDiariesHint: String,
    val settings: String,
    val backgroundImage: String,
    val theme: String,
    val glassTransparency: String,
    val animations: String,
    val animationsHint: String,
    val language: String,
    val livePreview: String,
    val livePreviewHint: String,
    val edit: String,
    val save: String,
    val lyric: String,
    val writing: String,
    val diaryNote: String,
    val writePlaceholder: String,
    val delete: String
)

fun appStrings(language: String): AppStrings {
    return AppStrings(
        appSubtitle = "记录每一首歌陪你的时刻",
        createEntry = "新建记录",
        songCover = "歌曲封面",
        song = "歌曲名",
        artist = "歌手",
        date = "日期",
        moodQuestion = "今天是什么心情？",
        lyricSnippet = "歌词片段（可选）",
        createButton = "保存这首歌",
        allDiaries = "最近记录",
        noDiaries = "还没有日记",
        noDiariesHint = "写下第一首歌，开始你的 innocence。",
        settings = "个性化",
        backgroundImage = "背景图片",
        theme = "主题色",
        glassTransparency = "卡片透明度",
        animations = "动效",
        animationsHint = "保留轻微的进入和切换动画",
        language = if (language == "English") "语言" else "语言",
        livePreview = "预览效果",
        livePreviewHint = "这里会实时显示日记卡片的透明度与排版。",
        edit = "编辑",
        save = "保存",
        lyric = "加入歌词",
        writing = "写感想",
        diaryNote = "日记正文",
        writePlaceholder = "把这一刻的情绪写下来……",
        delete = "删除"
    )
}
